import type { CreateHabitInput } from "@/lib/api-client";

export type CatalogHabit = CreateHabitInput & {
  id: string;
  category: string;
  description: string;
};

export const HABIT_CATALOG: CatalogHabit[] = [
  {
    id: "meditate",
    category: "Mindfulness",
    description: "Start the day with calm focus.",
    name: "Morning meditation",
    icon: "Brain",
    frequencyType: "DAILY",
    targetTime: "07:00",
    endTime: "07:15",
    durationMinutes: 15,
    reminderEnabled: true,
  },
  {
    id: "water",
    category: "Health",
    description: "Stay hydrated throughout the day.",
    name: "Drink water",
    icon: "Droplets",
    frequencyType: "DAILY",
    targetTime: "09:00",
    endTime: "18:00",
    durationMinutes: 60,
    reminderEnabled: true,
  },
  {
    id: "exercise",
    category: "Fitness",
    description: "Move your body and boost energy.",
    name: "Workout",
    icon: "Dumbbell",
    frequencyType: "WEEKDAYS",
    weekdays: [1, 2, 3, 4, 5],
    targetTime: "06:30",
    endTime: "07:15",
    durationMinutes: 45,
    reminderEnabled: true,
  },
  {
    id: "read",
    category: "Growth",
    description: "Read something meaningful daily.",
    name: "Read 20 minutes",
    icon: "BookOpen",
    frequencyType: "DAILY",
    targetTime: "21:00",
    endTime: "21:20",
    durationMinutes: 20,
    reminderEnabled: false,
  },
  {
    id: "journal",
    category: "Reflection",
    description: "Reflect on your day before bed.",
    name: "Evening journal",
    icon: "PenLine",
    frequencyType: "DAILY",
    targetTime: "21:30",
    endTime: "21:45",
    durationMinutes: 15,
    reminderEnabled: true,
  },
  {
    id: "walk",
    category: "Health",
    description: "A light walk clears the mind.",
    name: "Daily walk",
    icon: "Waves",
    frequencyType: "DAILY",
    targetTime: "17:00",
    endTime: "17:30",
    durationMinutes: 30,
    reminderEnabled: false,
  },
  {
    id: "stretch",
    category: "Fitness",
    description: "Loosen up after sitting all day.",
    name: "Stretch routine",
    icon: "Target",
    frequencyType: "WEEKDAYS",
    weekdays: [1, 2, 3, 4, 5],
    targetTime: "08:00",
    endTime: "08:10",
    durationMinutes: 10,
    reminderEnabled: false,
  },
  {
    id: "sleep",
    category: "Health",
    description: "Wind down for better rest.",
    name: "Sleep by 11pm",
    icon: "Moon",
    frequencyType: "DAILY",
    targetTime: "22:30",
    endTime: "23:00",
    durationMinutes: 30,
    reminderEnabled: true,
  },
  {
    id: "vitamins",
    category: "Health",
    description: "Don't forget daily supplements.",
    name: "Take vitamins",
    icon: "Heart",
    frequencyType: "DAILY",
    targetTime: "08:00",
    endTime: "08:05",
    durationMinutes: 5,
    reminderEnabled: true,
  },
];
